export {default as MyButton} from './MyButton.vue'
export {default as MyInput} from './MyInput.vue'
export {default as MyModal} from './MyModal.vue'
export {default as MyAnchor} from './MyAnchor.vue'
export * from './some-util-mod'
